#!/bin/bash

read -p "Digite o nome do primeiro diretório a ser listado: " one
read -p "Digite o nome do segundo diretório a ser listado: " two
read -p "Digite o nome do terceiro diretório a ser listado: " three
ls $one $two $three
