#!/bin/bash

read -p "Digte o nome dos arquivos: " arq1 arq2 arq3
linhas1=$(cat $arq1 | wc -l)
linhas2=$(cat $arq2 | wc -l)
linhas3=$(cat $arq3 | wc -l)

(($linhas1 > $linhas2)) && (($linhas1 > $linhas2)) && echo $arq1
(($linhas2 > $linhas1)) && (($linhas2 > $linhas3)) && echo $arq2
(($linhas3 > $linhas1)) && (($linhas3 > $linhas2)) && echo $arq3
